services:
  postgres17:
    image: postgres:17-alpine3.20
    network_mode: bridge
    container_name: postgres
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    expose:
      - 5433
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=people
      - POSTGRES_USER=yuji
      - POSTGRES_PASSWORD=Password123
    restart: unless-stopped
  # APP*****************************************
#  reactiveTalk:
#    image: reactive-talk
#    network_mode: bridge
#    container_name: reactive-talk
#    context: .
#    expose:
#      - 8080
#    ports:
#      - 8080:8080
#    restart: unless-stopped
#    depends_on:
#      - postgres
#    links:
#      - postgres
#volumes:
#  postgres-data:
